import React, { useState, useEffect } from 'react';
import {
    View,
    Text,
    FlatList,
    TouchableOpacity,
    StyleSheet,
    ActivityIndicator,
    Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import axios from 'axios';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { API_URL } from '../config/api';
import Background from '../components/Background';

type Props = {
    userId: number;
    onBack: () => void;
    showImage?: boolean;
};

type Assessment = {
    id: number;
    userId: number;
    assessmentDate: string;
    score: number;
    maxScore: number;
    riskLevel: string;
};

export default function HistoryScreen({ userId, onBack, showImage = false }: Props) {
    const [assessments, setAssessments] = useState<Assessment[]>([]);
    const [loading, setLoading] = useState(true);
    const [exporting, setExporting] = useState(false);

    useEffect(() => { fetchHistory(); }, []);

    const fetchHistory = async () => {
        try {
            const res = await axios.get(`${API_URL}/assessments/user/${userId}`);
            setAssessments(res.data);
        } catch (error) { console.error(error); } finally { setLoading(false); }
    };

    const getRiskColor = (risk: string) => {
        switch (risk) {
            case 'Low': return '#22C55E';
            case 'Moderate': return '#F59E0B';
            case 'High': return '#E67E22';
            case 'Severe': return '#EF4444';
            default: return '#6B7280';
        }
    };

    const formatDate = (dateStr: string) => {
        if (!dateStr) return 'No date';
        const d = new Date(dateStr);
        return isNaN(d.getTime()) ? 'Invalid Date' : d.toLocaleString();
    };

    const exportPDF = async () => {
        if (assessments.length === 0) {
            Alert.alert('No Data', 'You have no assessments to export.');
            return;
        }
        setExporting(true);
        const html = `
      <html><head><style>
        body { font-family: Arial; padding: 30px; }
        h1 { color: #2563EB; text-align: center; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #2563EB; color: white; padding: 10px; text-align: left; }
        td { padding: 10px; border-bottom: 1px solid #ddd; }
        .low { color: #22C55E; font-weight: bold; }
        .moderate { color: #F59E0B; font-weight: bold; }
        .high { color: #E67E22; font-weight: bold; }
        .severe { color: #EF4444; font-weight: bold; }
      </style></head>
      <body>
        <h1>🧠 WELLNEST — Assessment History</h1>
        <p>Generated: ${new Date().toLocaleString()}</p>
        <p><strong>Total Assessments:</strong> ${assessments.length}</p>
        <table>
          <tr><th>#</th><th>Score</th><th>Risk</th><th>Date</th></tr>
          ${assessments.map((a, i) => `
            <tr>
              <td>${i + 1}</td>
              <td>${a.score}/${a.maxScore}</td>
              <td class="${a.riskLevel.toLowerCase()}">${a.riskLevel}</td>
              <td>${new Date(a.assessmentDate).toLocaleDateString()}</td>
            </tr>
          `).join('')}
        </table>
        <p style="margin-top:40px;text-align:center;color:#6B7280;font-size:12px;">Generated by WELLNEST</p>
      </body></html>
    `;
        try {
            const { uri } = await Print.printToFileAsync({ html });
            await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Export History' });
        } catch (error) { Alert.alert('Error', 'Failed to generate PDF.'); } finally { setExporting(false); }
    };

    if (loading) {
        return (
            <Background showImage={showImage}>
                <View style={styles.center}><ActivityIndicator size="large" color="#2563EB" /></View>
            </Background>
        );
    }

    return (
        <Background showImage={showImage}>
            <View style={styles.container}>
                <View style={styles.header}>
                    <TouchableOpacity onPress={onBack}><Text style={styles.backText}>← Back</Text></TouchableOpacity>
                    <Text style={styles.title}>History</Text><View style={{ width: 50 }} />
                </View>

                {assessments.length > 0 && (
                    <>
                        <LinearGradient colors={['#ffffff', '#f0f4ff']} style={styles.statsBox}>
                            <Text style={styles.statsNumber}>{assessments.length}</Text>
                            <Text style={styles.statsLabel}>Total Assessments</Text>
                        </LinearGradient>

                        <LinearGradient colors={['#E67E22', '#F59E0B']} style={styles.exportBtn}>
                            <TouchableOpacity onPress={exportPDF} disabled={exporting} style={styles.exportBtnInner}>
                                <Text style={styles.exportBtnText}>{exporting ? 'Generating...' : '📄 Export PDF'}</Text>
                            </TouchableOpacity>
                        </LinearGradient>
                    </>
                )}

                <FlatList
                    data={assessments}
                    keyExtractor={(item) => item.id.toString()}
                    renderItem={({ item }) => (
                        <LinearGradient colors={['#ffffff', '#f8fafc']} style={styles.card}>
                            <View style={styles.cardRow}>
                                <Text style={styles.cardScore}>{item.score}/{item.maxScore}</Text>
                                <View style={{ backgroundColor: getRiskColor(item.riskLevel) + '20', paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12 }}>
                                    <Text style={{ color: getRiskColor(item.riskLevel), fontWeight: 'bold' }}>{item.riskLevel}</Text>
                                </View>
                            </View>
                            <Text style={styles.cardDate}>{formatDate(item.assessmentDate)}</Text>
                        </LinearGradient>
                    )}
                    ListEmptyComponent={<Text style={styles.emptyText}>No assessments yet.</Text>}
                />
            </View>
        </Background>
    );
}

const styles = StyleSheet.create({
    container: { flex: 1, padding: 20 },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
    backText: { fontSize: 16, color: '#2563EB', fontWeight: '600' },
    title: { fontSize: 22, fontWeight: 'bold', color: '#111827' },
    statsBox: { padding: 16, borderRadius: 12, alignItems: 'center', marginBottom: 12 },
    statsNumber: { fontSize: 28, fontWeight: 'bold', color: '#2563EB' },
    statsLabel: { fontSize: 14, color: '#6B7280', marginTop: 4 },
    exportBtn: { borderRadius: 12, overflow: 'hidden', marginBottom: 16 },
    exportBtnInner: { padding: 14, alignItems: 'center' },
    exportBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
    card: { padding: 16, borderRadius: 12, marginBottom: 10, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2 },
    cardRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    cardScore: { fontSize: 18, fontWeight: 'bold', color: '#111827' },
    cardDate: { fontSize: 14, color: '#6B7280', marginTop: 4 },
    emptyText: { textAlign: 'center', color: '#6B7280', marginTop: 40, fontSize: 16 },
});